repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # or latest
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: run-django-tests
        name: Run Django Tests
        entry: /Users/Jacob_Ide/alex/venv/bin/python3 manage.py test
        language: system
        types: [python]
        pass_filenames: false
