services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      args:
        ENVIRONMENT: staging
    env_file: .env.staging
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
