# Generated by Django 5.2.3 on 2025-06-16 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("creator", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "fiction_non_fiction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Non-Fiction", "Non-Fiction"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("creator", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("creator", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("director", models.CharField(blank=True, max_length=255)),
                ("runtime_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DVD", "DVD"),
                            ("Blu-ray", "Blu-ray"),
                            ("Digital", "Digital"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("creator", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("artist", models.CharField(blank=True, max_length=255)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CD", "CD"),
                            ("Vinyl", "Vinyl"),
                            ("Digital", "Digital"),
                        ],
                        max_length=50,
                    ),
                ),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
